- name: split input into 'path' and 'name'
  set_fact:
    path: "{{ outer_item.split('/')[0] }}"
    name: "{{ outer_item.split('/')[1] }}"

- debug: 
    msg: "Installing: {{ name }}"
    
- name: create temporary directory
  tempfile:
    state: directory
    suffix: addon
  register: tmpdir
  changed_when: false
    
- name: Download add on
  get_url:
    url: "https://addons.mozilla.org/firefox/downloads/file/{{ path }}/{{ name }}"
    dest: "{{ tmpdir.path }}/{{ name }}"
 
- name: unzip addon in temp directory
  unarchive:
    src: "{{ tmpdir.path }}/{{ name }}"
    dest: "{{ tmpdir.path }}"
  changed_when: false
  
- name: check if 'mozilla-recommendation.json' file exists
  stat: 
    path: "{{ tmpdir.path }}/mozilla-recommendation.json"
  register: mozilla_recommendation
  
- name: include based on variable
  include_tasks: "{{ mozilla_recommendation.stat.exists | ternary('mozilla_recommendation', 'manifest') }}_installer.yml"

