- name: Check that the .gitconf exists
  stat:
    path: ~/.gitconfig
  register: gitconfig_exists
  
- name: set minimal git config
  command: "git config --global {{ item }}"
  with_items: 
  - "user.email {{ git_email }}"
  - "user.name {{ git_username }}"
  when: not gitconfig_exists.stat.exists
  
- name: Check that the ssh key exists
  stat:
    path: ~/.ssh/id_rsa
  register: key_exists
  
- name: Generate SSH key.
  command: "ssh-keygen -t rsa -b 4096 -N \"\" -C {{ansible_hostname}} -f ~/.ssh/id_rsa"
  when: not key_exists.stat.exists

- name: Read SSH public key.
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_public_key
  changed_when: false
     
- name: Add public ssh key to github
  uri:
    url: https://api.github.com/user/keys
    method: POST
    headers:
      Authorization: "token {{ github_auth_token }}"
    body: 
      title: "{{ansible_hostname}}"
      key: "{{ ssh_public_key.stdout }}"
    body_format: json
    status_code: 201
  changed_when: false 
